### PR TITLE
added [defs, clipPath, path, g, d, fill, viewBox] Svg nodes and attributes 

### PR DESCRIPTION
**Pull request by pdamoc**
These are among the most frequently used.

### CODE REVIEW

**Comment by mbylstra** [comment]
Great, thanks for this! I'll deploy it gh-pages.

**Comment by mbylstra** [comment]
That's been publish. Here's a little test you can paste in to see it working:

```
<svg viewBox="1,2,3,4" >
  <g>
    <defs>
    </defs>
    <path d="somenumbersandletters" fill="red" clipPath="somenumbersandletters">
    </path>
    <clipPath fill="red">
    </clipPath>
  </g>
</svg>
```
I realise that is nonsensical SVG, but you can see that it is parsing those tags and attributes.

**Comment by pdamoc** [comment]
Hi Michael, I know that it works as I've tested it with a more complex SVG in my fork before creating the the PR. :)

Now, the main challenge is around attributes that clash with nodes as it is the case for `clipPath` and with attributes that solve to a non-obvious name as it is the case with `xmlns -> xmlSpace`

**Comment by mbylstra** [comment]
Let's move this conversation to the open SVG issue. I hope you don't mind me referencing your comment.

**Pull request merged**
